name: Hi3798MV100 固件编译

on:
  push:
    branches: [main]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 用官方Ubuntu镜像，不依赖私有容器
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libssl-dev \
            git wget unzip flex bison make gcc g++ python3

      - name: 下载并安装工具链
        run: |
          wget https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
          sudo tar -xf gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
          echo "PATH=/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin:$PATH" >> $GITHUB_ENV
          echo "ARCH=arm" >> $GITHUB_ENV
          echo "CROSS_COMPILE=arm-linux-gnueabihf-" >> $GITHUB_ENV

      - name: 配置内核（启用驱动）
        run: |
          make hi3798mv100_defconfig
          # 启用RTL8188FTV驱动
          echo "CONFIG_RTL8188FTV=m" >> .config
          echo "CONFIG_RTL8188FTV_POWER_MGMT=y" >> .config
          # 启用USB打印支持
          echo "CONFIG_USB_PRINTER=y" >> .config
          echo "CONFIG_USB_PRINTER_CLASS=y" >> .config
          make olddefconfig  # 应用配置

      - name: 编译固件
        run: |
          make -j$(nproc)
          mkdir -p output
          find . -name "*.bin" -exec cp {} output/ \;
          tar -czvf hi3798mv100-firmware.tar.gz output/

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: hi3798mv100-firmware
          path: hi3798mv100-firmware.tar.gz
