name: Hi3798mv100在线编译（完整开启USB打印功能）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
        with:
          repository: zjkanjie/HiSTBLinuxV100R005C00SPC060
          path: HiSTBLinux

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt remove -y make
          wget http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_3.81-8.2ubuntu3_amd64.deb
          sudo dpkg -i make_3.81-8.2ubuntu3_amd64.deb
          sudo apt install -y gcc-arm-linux-gnueabihf gettext bison flex bc zlib1g-dev libncurses5-dev lzma git build-essential
          sudo ln -sf /bin/bash /bin/sh

      - name: 准备内核源码
        run: |
          cd HiSTBLinux
          mkdir -p third_party/open_source/
          wget https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.4.35.tar.gz -O third_party/open_source/linux-4.4.35.tar.gz
          rm -rf source/kernel/linux-4.4.y
          tar -zxf third_party/open_source/linux-4.4.35.tar.gz -C source/kernel/
          mv source/kernel/linux-4.4.35 source/kernel/linux-4.4.y

      - name: 设置环境变量
        run: |
          cd HiSTBLinux
          cat > env.sh << 'EOF'
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabihf-
          export PATH=/usr/bin:$PATH
          EOF
          source ./env.sh

      - name: 生成.config
        run: |
          cd HiSTBLinux
          source ./env.sh
          cp configs/hi3798mv100/hi3798mdmo1g_hi3798mv100_cfg.mak ./cfg.mak
          KERNEL_DIR="source/kernel/linux-4.4.y"
          cd $KERNEL_DIR
          make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE multi_v7_defconfig V=1

      - name: 清理并生成dtc文件
        run: |
          cd HiSTBLinux
          source ./env.sh
          KERNEL_DIR="source/kernel/linux-4.4.y"
          cd $KERNEL_DIR
          make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE scripts/dtc clean V=1
          make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE scripts/dtc V=1
          sed -i 's/^extern YYLTYPE yylloc;/#extern YYLTYPE yylloc;/' scripts/dtc/dtc-lexer.lex.c

      - name: 配置内核功能（明确开启USB打印）
        run: |
          cd HiSTBLinux
          source ./env.sh
          cd source/kernel/linux-4.4.y
          # 1. 启用USB核心支持
          sed -i '/CONFIG_USB=/d' .config
          echo "CONFIG_USB=y" >> .config  # 开启USB子系统

          # 2. 启用USB控制器驱动（兼容不同接口的打印机）
          sed -i '/CONFIG_USB_UHCI_HCD=/d' .config
          sed -i '/CONFIG_USB_OHCI_HCD=/d' .config
          sed -i '/CONFIG_USB_EHCI_HCD=/d' .config
          echo "CONFIG_USB_UHCI_HCD=y" >> .config  # 支持USB 1.1（UHCI控制器）
          echo "CONFIG_USB_OHCI_HCD=y" >> .config  # 支持USB 1.1（OHCI控制器）
          echo "CONFIG_USB_EHCI_HCD=y" >> .config  # 支持USB 2.0（EHCI控制器）

          # 3. 启用USB打印机驱动（核心功能）
          sed -i '/CONFIG_USB_PRINTER=/d' .config
          echo "CONFIG_USB_PRINTER=y" >> .config  # 内置USB打印机驱动

          # 4. 其他必要功能（Docker依赖等）
          echo "CONFIG_DEVTMPFS=y" >> .config
          echo "CONFIG_CGROUPS=y" >> .config
          echo "CONFIG_RTL8188FTV=y" >> .config

          # 验证USB打印配置是否生效
          echo "=== 验证USB打印配置 ==="
          grep "CONFIG_USB=y" .config
          grep "CONFIG_USB_PRINTER=y" .config
          grep "CONFIG_USB_EHCI_HCD=y" .config

      - name: 编译内核和固件
        run: |
          cd HiSTBLinux
          source ./env.sh
          make linux -j4 2>&1 | tee kernel.log
          make build -j4 2>&1 | tee build.log

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: hi3798mv100-firmware
          path: |
            HiSTBLinux/out/hi3798mv100/*
            HiSTBLinux/kernel.log
            HiSTBLinux/build.log
