name: Hi3798MV100 固件编译

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 编译 Hi3798MV100 固件
    runs-on: ubuntu-latest
    container:
      image: hisilicon/hi3798mv100-sdk:latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 设置环境变量
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-hisiv300-linux-
          export PATH=$PATH:/opt/hisilicon/toolchains/arm-hisiv300-linux/bin

      - name: 内核配置
        run: |
          make hi3798mv100_defconfig
          make menuconfig -silentoldconfig <<EOF
          # 交互式配置选项
          EOF

      - name: 启用 RTL8188FTV 驱动
        run: |
          sed -i 's/# CONFIG_RTL8188FTV is not set/CONFIG_RTL8188FTV=m/g' .config
          sed -i 's/# CONFIG_RTL8188FTV_POWER_MGMT is not set/CONFIG_RTL8188FTV_POWER_MGMT=y/g' .config

      - name: 启用 USB 打印支持
        run: |
          sed -i 's/# CONFIG_USB_PRINTER is not set/CONFIG_USB_PRINTER=y/g' .config
          sed -i 's/# CONFIG_USB_PRINTER_CLASS is not set/CONFIG_USB_PRINTER_CLASS=y/g' .config
          sed -i 's/# CONFIG_USB_PRINTER_DEBUG is not set/CONFIG_USB_PRINTER_DEBUG=y/g' .config

      - name: 配置内存为 1GB + 8GB
        run: |
          sed -i 's/memory@0x00000000/
            memory@0x00000000 {
              device_type = "memory";
              reg = <0x00000000 0x40000000>; // 1GB 内存
            };
            memory@0x40000000 {
              device_type = "memory";
              reg = <0x40000000 0x20000000>; // 8GB 扩展内存
            }/g' arch/arm/boot/dts/hi3798mv100.dts

      - name: 编译内核
        run: |
          make -j$(nproc)

      - name: 编译设备树
        run: |
          make dtbs

      - name: 编译 u-boot
        run: |
          make u-boot

      - name: 生成镜像
        run: |
          make image

      - name: 打包固件
        run: |
          mkdir -p output
          cp out/hi3798mv100/hi_kernel.bin output/
          cp out/hi3798mv100/fastboot-burn.bin output/
          cp out/hi3798mv100/bootargs.bin output/
          tar -czvf hi3798mv100-firmware.tar.gz output/

      - name: 上传固件包
        uses: actions/upload-artifact@v4
        with:
          name: hi3798mv100-firmware
          path: hi3798mv100-firmware.tar.gz
