name: Build EC6108V9 Firmware

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build-ec6108v9:
    runs-on: ubuntu-22.04
    timeout-minutes: 360  # 最大6小时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses5-dev \
          bc \
          flex \
          bison \
          libssl-dev \
          git \
          wget \
          unzip \
          python3 \
          gettext \
          lzma \
          zlib1g-dev

    - name: Prepare SDK environment
      run: |
        # 设置配置文件
        cp configs/hi3798mv100/hi3798mdmo1g_hi3798mv100_cfg.mak ./cfg.mak
        
        # 设置环境变量
        echo "export ARCH=arm" >> $GITHUB_ENV
        echo "export CROSS_COMPILE=arm-hisiv300-linux-" >> $GITHUB_ENV

    - name: Configure kernel for EC6108V9
      run: |
        cd source/kernel/linux-4.4.y
        
        # 应用基础配置
        make hi3798mv100_defconfig
        
        # 启用USB打印支持
        ./scripts/config --enable CONFIG_USB_PRINTER
        ./scripts/config --enable CONFIG_USB
        
        # 启用rt8188ftv驱动 (假设驱动在源码中)
        ./scripts/config --module CONFIG_RTL8188FU
        
        # 启用Docker需要的功能
        ./scripts/config --enable CONFIG_DEVTMPFS
        ./scripts/config --enable CONFIG_CGROUPS
        ./scripts/config --enable CONFIG_NAMESPACES
        ./scripts/config --enable CONFIG_NET_NS
        ./scripts/config --enable CONFIG_PID_NS
        ./scripts/config --enable CONFIG_IPC_NS
        ./scripts/config --enable CONFIG_UTS_NS
        ./scripts/config --enable CONFIG_USER_NS
        
        # 保存配置
        make savedefconfig
        cp defconfig arch/arm/configs/hi3798mv100_defconfig
        
        cd ../..

    - name: Build firmware
      run: |
        # 初始化SDK环境
        source env.sh
        
        # 开始编译
        make build -j$(($(nproc) * 2)) 2>&1 | tee build.log
        
        # 检查编译产物
        ls -lh out/hi3798mv100/

    - name: Archive firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ec6108v9-firmware
        path: |
          out/hi3798mv100/fastboot-burn.bin
          out/hi3798mv100/bootargs.bin
          out/hi3798mv100/hi_kernel.bin
          build.log
