name: 编译Hi3798mv100固件（RT8188FTV+USB打印+CUPS）

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 拉取源码仓库
        uses: actions/checkout@v4
        with:
          repository: zjkanjie/HiSTBLinuxV100R005C00SPC060
          path: HiSTBLinux

      - name: 安装依赖（含指定版本make）
        run: |
          sudo apt update
          # 卸载系统默认的make 4.3
          sudo apt remove -y make
          # 安装依赖工具
          sudo apt install -y gcc-arm-linux-gnueabihf gettext bison flex bc zlib1g-dev libncurses5-dev lzma git build-essential wget
          # 手动下载并安装make 3.81（脚本要求的版本）
          wget http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_3.81-8.2ubuntu3_amd64.deb
          sudo dpkg -i make_3.81-8.2ubuntu3_amd64.deb
          # 修复sh链接为bash
          sudo ln -sf /bin/bash /bin/sh
          # 验证make版本
          make --version

      - name: 准备RT8188FTV驱动源码
        run: |
          cd HiSTBLinux
          mkdir -p third_party/open_source/rtl8188ftv
          git clone https://github.com/kelebek333/rtl8188fu.git third_party/open_source/rtl8188ftv

      - name: 初始化SDK环境（兼容make 3.81）
        run: |
          cd HiSTBLinux
          bash server_install.sh  # 此时make版本符合要求，可正常执行
          cp configs/hi3798mv100/hi3798mdmo1g_hi3798mv100_cfg.mak ./cfg.mak
          source ./env.sh
          env > sdk_env.txt

      - name: 修改内核配置
        run: |
          cd HiSTBLinux
          source sdk_env.txt
          cd source/kernel/linux-4.4.y
          cp ../../../../hi3798mv100_defconfig arch/arm/configs/
          make ARCH=arm hi3798mv100_defconfig
          # 添加必要配置
          sed -i '/CONFIG_USB_PRINTER/d' .config
          echo "CONFIG_USB=y" >> .config
          echo "CONFIG_USB_UHCI_HCD=y" >> .config
          echo "CONFIG_USB_OHCI_HCD=y" >> .config
          echo "CONFIG_USB_EHCI_HCD=y" >> .config
          echo "CONFIG_USB_PRINTER=y" >> .config
          echo "CONFIG_CGROUPS=y" >> .config
          echo "CONFIG_CGROUP_DEVICE=y" >> .config
          echo "CONFIG_CGROUP_CPUACCT=y" >> .config
          echo "CONFIG_DEVTMPFS=y" >> .config
          echo "CONFIG_DEVTMPFS_MOUNT=y" >> .config
          echo "CONFIG_FHANDLE=y" >> .config
          echo "CONFIG_CFG80211=y" >> .config
          echo "CONFIG_MAC80211=y" >> .config
          echo "CONFIG_RTL8188FTV=y" >> .config
          echo "CONFIG_RTLWIFI=y" >> .config
          echo "CONFIG_RTLWIFI_USB=y" >> .config
          echo "CONFIG_WIRELESS_EXT=y" >> .config
          echo "CONFIG_WEXT_CORE=y" >> .config
          make ARCH=arm savedefconfig
          cp defconfig arch/arm/configs/hi3798mv100_defconfig

      - name: 编译固件
        run: |
          cd HiSTBLinux
          source sdk_env.txt
          make build -j4 2>&1 | tee build.log
          mkbootargs -s 64 -r bootargs_input.txt -o out/hi3798mv100/bootargs.bin

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: hi3798mv100-firmware-usb-print
          path: |
            HiSTBLinux/out/hi3798mv100/*
            HiSTBLinux/build.log
